# Generated by Django 5.0 on 2024-01-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_bookmarks_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isBookmark',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
