# Generated by Django 5.0 on 2024-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_isbookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='post',
            name='relatedVideo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
