# Generated by Django 5.0 on 2024-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_relatedvideo_post_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tutorial_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
